[env]
COLIMA_HOME = "{{config_root}}/.colima"
COLIMA_PROFILE = "systemd-ts"
LIMA_HOME = "{{config_root}}/.colima/_lima"

[tools]
colima = "0.10.1"
lima = "2.0.2"
node = "26.1.0"
pnpm = "11.0.8"
viteplus = "0.1.20"
