[env]
COLIMA_HOME = "{{config_root}}/.colima"
COLIMA_PROFILE = "systemd-ts"
LIMA_HOME = "{{config_root}}/.colima/_lima"

[tools]
colima = "0.10.3"
docker-cli = "29.5.3"
lima = "2.1.2"
ni = "30.1.0"
node = "26.3.0"
pnpm = "11.5.3"
viteplus = "0.1.24"
