packages:
  - packages/*
  - tools/*

catalogMode: prefer
blockExoticSubdeps: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@typescript/*"

catalog:
  "@changesets/cli": 3.0.0
  "@types/node": 25.9.5
  "@typescript/native-preview": 7.0.0-dev.20260707.2
  cspell: 10.0.1
  oxfmt: 0.64.0
  pin-dependencies-checker: 2.7.1
  tar: 7.5.22
  typescript: 7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.10
  vite-plus: 0.2.9
  takua: 0.2.2

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
