packages:
  - packages/*
  - tools/*

catalogMode: prefer
blockExoticSubdeps: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@typescript/*"

catalog:
  "@changesets/cli": 2.31.0
  "@types/node": 25.9.1
  "@typescript/native-preview": 7.0.0-dev.20260526.1
  cspell: 10.0.0
  pin-dependencies-checker: 2.7.1
  tar: 7.5.15
  typescript: 6.0.3
  vite: npm:@voidzero-dev/vite-plus-core@0.1.22
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.22
  vite-plus: 0.1.22
  takua: 0.2.1

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
